#!/bin/sh

echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --  "Checking for updates..";

#################
# PULLING FILES #
#################

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@";
cd $HOME/cableguardianupdates/;
PULL_OUT=`git pull 2>&1`;
echo $PULL_OUT;
case "$PULL_OUT" in
	*"Updating"* ) 
		FOUND=true;
		echo "";;
	* )
		FOUND=false;
		echo "";;
esac

if [ $FOUND ]; then

#################
# STOP  SERVICE #
#################
	
	echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --  `service cable_guardian stop`;

#################
#  COPY  FILES  #
#################


	cp -v $HOME/cableguardianupdates/CableGuardian.jar $HOME/;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated CableGuardian.jar;
	
	echo '\n\n';
	rm -rf /var/www/html/*;
	cp -vr $HOME/cableguardianupdates/www/* /var/www/html/;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated /var/www/html folder;


	cp -v $HOME/cableguardianupdates/CBUpdater $HOME/;
	chmod +x $HOME/CBUpdater;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated CBUpdater;
	
	cp -v $HOME/cableguardianupdates/deploy $HOME;
	chmod +x $HOME/deploy;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated deploy;


#################
#?RUN  DEPLOYER?#
#################

	$HOME/cableguardianupdates/deploy >> /var/log/cable_guardian/deploy_log;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Executed deployer;

#################
# SETTING  TIME #
#################

#   deploy does it already, activate this option only if deploy script is disabled.

#	ntpdate -b -s -u pool.ntp.org;
#	hwclock -w -f /dev/rtc1;

#################
# START SERVICE #
#################

	echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --  `service cable_guardian start`;


fi

