#!/bin/sh

echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --  "Checking for updates..";

#################
# PULLING FILES #
#################

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@";
cd $HOME/cableguardianupdates/;
PULL_OUT=`git pull 2>&1`;

while true ; do
        case "$PULL_OUT" in
                *"up-to-date"* )
                        FOUND=0;
                        echo "";
                        break;;
                *"changed"* )
                        FOUND=1;
                        echo "";
                        break;;
        esac
done

echo $PULL_OUT;


if [ $FOUND -eq 1 ]; then

#################
# STOP  SERVICE #
#################

	echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --  `service cable_guardian stop`;

#################
#  COPY  FILES  #
#################

	echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --------------------------------- >> /var/log/cable_guardian/copy_log;
	cp -v $HOME/cableguardianupdates/CableGuardian.jar /etc/init.d/  >> /var/log/cable_guardian/copy_log;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated CableGuardian.jar;

	echo '\n\n';
	rm -rf /var/www/html/*;
	cp -vr $HOME/cableguardianupdates/www/* /var/www/html/ >> /var/log/cable_guardian/copy_log;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated /var/www/html folder;


	cp -v $HOME/cableguardianupdates/CBUpdater $HOME/ >> /var/log/cable_guardian/copy_log;
	chmod +x $HOME/CBUpdater;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated CBUpdater;

	cp -v $HOME/cableguardianupdates/deploy $HOME >> /var/log/cable_guardian/copy_log;
	chmod +x $HOME/deploy;
	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Updated deploy;

	echo '\n\n----------------Done with copied files for this update-------------';
        echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` ------------------$;
 


#################
#?RUN  DEPLOYER?#
#################

#	$HOME/cableguardianupdates/deploy >> /var/log/cable_guardian/deploy_log;
#	echo `date | awk '{print $3" "$2" "$6"  "$4}'` -- Executed deployer;

#################
# SETTING  TIME #
#################

#   deploy does it already, activate this option only if deploy script is disabled.

#	ntpdate -b -s -u pool.ntp.org;
#	hwclock -w -f /dev/rtc1;

#################
# START SERVICE #
#################

	echo '\n\n'`date | awk '{print $3" "$2" "$6"  "$4}'` --  `service cable_guardian start`;


fi

